version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

    groups:
      # Always update Angular packages together
      angular:
        applies-to: version-updates
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@schematics/angular'
      angular-security:
        applies-to: security-updates
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@schematics/angular'
      # Dev tools have been bundled
      dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'

    ignore:
      # Manually trigger Angular major updates using `ng update` (runs migrations)
      - dependency-name: '@angular/*'
        update-types: ['version-update:semver-major']
      - dependency-name: '@angular-devkit/*'
        update-types: ['version-update:semver-major']
      - dependency-name: '@schematics/angular'
        update-types: ['version-update:semver-major']
      # Angular supports only certain versions of TypeScript; `ng update` automatically updates TypeScript accordingly
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
